### PR TITLE
Parameterize integration tests, test multiple versions of Pilosa

### PR DESCRIPTION
**Pull request by codysoyland**
Move integration test orchestration into Makefile
Simplify .travis.yml
Add multiple Pilosa versions to build matrix

### CODE REVIEW

**Comment by yuce** [comment]
I think many of the tests don't run, coverage dropped quit a bit.

**Comment by codysoyland** [comment]
Thanks for the note @yuce, I had a syntax error in the build tags. Additionally, I continue to have trouble getting the coverage report to run in TravisCI. Something is killing the process before it is complete -- just a message: "signal: killed". I will switch gears for the time being, as I've sunk too much time into this. I want to look into other CI providers.

**Comment by yuce** [comment]
Thanks Cody,  `make cover` runs fine on local with your latest changes (but `make fast-cover` doesn't run most tests).

Maybe "signal:killed" is thrown on CI due to  insufficient memory (not sure how we can fix it though).

I think one thing we should consider is caching the Pilosa binary somewhere in order to not download it on subsequent runs.

**Comment by codysoyland** [comment]
That theory of why it gets killed makes sense... seems like resource utilization is the most likely culprit.

Agreed on caching. I enabled caching on the main pilosa repo, and I intend to add it to this repo once I get everything else working.

**Comment by codysoyland** [comment]
Closing in favor of #179.

**Pull request closed without merging**
