### PR TITLE
handle all errors, use pkg/errors to add context

### LINKED ISSUE #49: Client.ImportNode ignores error
```
 func (c *Client) importNode(request *internal.ImportRequest) error {
	data, _ := proto.Marshal(request)
	// request.Marshal never returns an error
```

`proto.Marshal` attempts to cast `request` to a `Marshaler`, but `*internal.ImportRequest` doesn't implement `Marshal()`,  so `proto.Marshal` goes down another path which it appears may return an error. We should probably just handle the error anywhere `proto.Marshal` is called regardless of whether the object in question is a `Marshaler` in order to be consistent, suppress warnings, and protect against future changes to generated code.

### PR DESCRIPTION
**Pull request by jaffee**
Fixes #49

### CODE REVIEW

**Comment by yuce** [comment]
It would be great to have tests to keep the coverage at 100%. I can add them too.

**Comment by jaffee** [comment]
hey @yuce - I can totally add the tests, I've got at least one more PR coming that may make some more invasive changes - do you mind if I wait until then to get the coverage back up to 100?

**Comment by yuce** [comment]
@jaffee  Sure! I guess the incoming changes build upon this PR? Would it make sense to include this PR on the coming PR ?

**Comment by yuce** [comment]
@jaffee I think https://github.com/pilosa/go-pilosa/pull/61covers everything in this PR. Is it OK to close this ?

**Comment by jaffee** [comment]
yep, good call

**Pull request closed without merging**
