### PR TITLE
1345 compatibility

### LINKED ISSUE #147: Rename `Frame` to `Field`
See: https://github.com/pilosa/pilosa/issues/1345

### LINKED ISSUE #148: Remove or rename/hide `Field` struct
See: https://github.com/pilosa/pilosa/issues/1345

### LINKED ISSUE #149: Remove/rename `AddIntField` and `OptFrameIntField` function options
See: https://github.com/pilosa/pilosa/issues/1345

### LINKED ISSUE #151: client.importValueNode does not check http response
importValueNode checks the error when making an http request, but does not check if the http response code is bad. This leads to swallowed errors if Pilosa has (e.g.) an InternalServerError

### PR DESCRIPTION
**Pull request by yuce**
Fixes #147 
Fixes #148 
Fixes #149 
Fixes #150 
Fixes #151

### CODE REVIEW

**Comment by jaffee** [comment]
We really need to stop doing these giant PRs. I understand that it's frustrating to wait for a review and merge before you can really move on, but as a reviewer, it's difficult to do a good job and tease apart the reasons behind each change. This makes it tempting to glance through everything, decide it looks good and hit approve - then we end up with difficult bugs that no one understands.

What @travisturner has been doing with his recent refactoring work is to submit a PR for one logical change, and then continue working on another branch which is based off of the first PR's branch. This allows the implementer to keep working while code review is happening, and makes it easier for the reviewer to give timely feedback. The reviewer MUST give timely feedback, however in case there are significant changes which would affect the follow-on work. If you're not getting a timely review, ping your reviewer on github, slack, and in standup. Reviewer - if you don't have time, for whatever reason, re-assign the review to someone else ASAP.

**Comment by yuce** [comment]
@jaffee The changes are mostly cosmetical, like renaming frame to field. If it's easier to review, I can create one PR per commit.

**Comment by jaffee** [comment]
I'll review this one - it is fairly digestible - sorry for the rant.

**Comment by yuce** [comment]
Thanks for the quick review. Hopefully the PRs that builds upon this one won't be as big.

**Comment by jaffee** [comment]
I meant to finish it yesterday morning and got distracted!

**Pull request merged**
